# Generated by Django 3.0.5 on 2020-04-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20200428_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversalltrips',
            name='rider_profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
