# Generated by Django 3.0.5 on 2020-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driversalltrips_rider_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversalltrips',
            name='rider_profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
