# Generated by Django 3.0.5 on 2020-04-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20200429_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversalltrips',
            name='rider_profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
