# Generated by Django 3.0.5 on 2020-04-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
